# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


#TWITTER_API_KEY: 
#TWITTER_SECRET_KEY: 

ACTIVE_API_KEY: 9kup34r9upvkkcnpquupxrzp

GOOGLE_MAPS_KEY: AIzaSyB4DxXvqtmIsUaUSaxvRhKaNlMk3R89780

#YELP KEYS:

YELP_CONSUMER_KEY: s25rOSXwkhrwoKIKTnzcSg
YELP_CONSUMER_SECRET: UthqFtpu_QJcxMg9jLrb1YnAJcY
YELP_TOKEN: IQOYkvrzQ7Voy662SSOWwYdxwXHj1iKp
YELP_TOKEN_SECRET: BHn6MFCoVYfX12lQ8G07SRHNjIs


MONGOLAB_URI: mongodb://heroku_app28602831:31t8fo98d782g1h6sqdth2ovmn@ds063449.mongolab.com:63449/heroku_app28602831
