# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


#TWITTER_API_KEY: 
#TWITTER_SECRET_KEY: 

ACTIVE_API_KEY: 9kup34r9upvkkcnpquupxrzp

GOOGLE_MAPS_KEY: AIzaSyB4DxXvqtmIsUaUSaxvRhKaNlMk3R89780

#YELP KEYS:

YELP_CONSUMER_KEY: s25rOSXwkhrwoKIKTnzcSg
YELP_CONSUMER_SECRET: UthqFtpu_QJcxMg9jLrb1YnAJcY
YELP_TOKEN: IQOYkvrzQ7Voy662SSOWwYdxwXHj1iKp
YELP_TOKEN_SECRET: BHn6MFCoVYfX12lQ8G07SRHNjIs

SECRET_KEY_BASE: 37c55abfd15605d604243200cfcb3e06d059d6ecda2b119d16d89fe7e548e20e21934c243f72b1688a2ffa0642d21980328c7f80b105906fd835c58cfe7af861

